server:
  port: 8081

spring:
  application:
    name: ingestion-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

cricapi:
  base-url: https://api.cricapi.com/v1
  api-key: ${CRICAPI_KEY:}

app:
  polling:
    interval-ms: 900000